### ISSUE TITLE
USB support for Windows filesystem exFAT, FAT, NTFS

### ISSUE THREAD

**Issue by atan2005** [xhikarishii/openwrt-ipq#5]
I have files that I would like to access through the device's USB port and the files have been extracted into a USB flash drive (as volume 4, designated d:) formatted with exFAT (or FAT or NTFS) partition being one of the 3 most commonly available filesystem types on Windows pc. 

````
DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
  Volume 0     C   OS           NTFS   Partition    458 GB  Healthy    Boot
  Volume 1         RESTORE      NTFS   Partition     17 GB  Healthy
  Volume 2         SYSTEM       FAT32  Partition    260 MB  Healthy    System
  Volume 3         RECOVERY     NTFS   Partition    950 MB  Healthy    Hidden
  Volume 4     D                exFAT  Removable   2000 MB  Healthy

C:\>dir d:
 Volume in drive D has no label.
 Volume Serial Number is 240D-1A8E

 Directory of d:\

13/06/2023  02:59 AM             1,740 md5.txt
13/06/2023  02:59 AM             5,710 contents.xml
30/07/2024  09:36 AM    <DIR>          update
12/07/2023  06:40 PM           915,410 Quectel_RG500Q-EA-AA_软件版本变更说明_V1301_01.200.01.200.pdf
12/07/2023  06:40 PM           852,693 Quectel_RG500Q-EA-AA_Firmware_Release_Notes_V1301_01.200.01.200.pdf
               4 File(s)      1,775,553 bytes
               1 Dir(s)   1,891,336,192 bytes free
````

Before inserting USB drive...
````
root@HikariWrt:/# ls -l /dev/sd*
ls: /dev/sd*: No such file or directory
````

After inserting USB drive...
````
root@HikariWrt:/# ls -l /dev/sd*
brw-------    1 root     root        8,   0 Jul 30 09:42 /dev/sda

root@HikariWrt:/# block info | grep "/dev/sd"
/dev/sda: UUID="240D-1A8E" TYPE="exfat"

root@HikariWrt:/# lsusb -t
/:  Bus 001.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 002.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 5000M
/:  Bus 003.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 004.Port 001: Dev 001, Class=root_hub, Driver=xhci-hcd/1p, 5000M
    |__ Port 001: Dev 002, If 0, Class=[unknown], Driver=option, 5000M
    |__ Port 001: Dev 002, If 1, Class=[unknown], Driver=option, 5000M
    |__ Port 001: Dev 002, If 2, Class=[unknown], Driver=option, 5000M
    |__ Port 001: Dev 002, If 3, Class=[unknown], Driver=option, 5000M
    |__ Port 001: Dev 002, If 4, Class=[unknown], Driver=qmi_wwan_q, 5000M
````

It detected the usb drive `/dev/sda` with exfat filesystem but it did not detect the first and only partition `/dev/sda1` with the extracted files in it. From further research, it lacks these packages `kmod-fs-exfat`, `kmod-fs-vfat`, `kmod-fs-ntfs3` to support the 3 most common filesystems on Windows. When these packages were tried to be installed, it complained about the incompatible version as below:-

![Screenshot 2024-07-30 at 11-20-56 HikariWrt - LuCI-System-Software-kmod-fs-exfat](https://github.com/user-attachments/assets/c7fb8062-79c4-46a0-8f56-e621406e675e)

![Screenshot 2024-07-30 at 11-21-41 HikariWrt - LuCI-System-Software-kmod-fs-vfat](https://github.com/user-attachments/assets/85f06a71-caad-41cc-b9bd-4ea30dfff833)

![Screenshot 2024-07-30 at 11-22-20 HikariWrt - LuCI-System-Software-kmod-fs-ntfs3](https://github.com/user-attachments/assets/4b681b57-e167-4c1c-b0f1-8306ecfa5d33)

````
root@HikariWrt:/# uname -r
6.6.37
````

Your firmware version of 6.6.37 versus new available version: 6.6.43 dated 30-Jul-2024 and going forward only newer snapshot versions will be available. Could you please advise how do I resolve the versions mismatch issue (or how to download version 6.6.37) and also going forward if more software are needed?

In @https://github.com/xhikarishii/openwrt-ipq, you have mentioned:
 
> To build your own firmware you need a GNU/Linux, BSD or macOS system (case sensitive filesystem required). Cygwin is unsupported because of the lack of a case sensitive file system.

However I don't have neither of the systems required above to be able to compile anything.

I am just following this up to see if you can instead provide the 3 required packages namely, kmod-fs-exfat, kmod-fs-vfat, kmod-fs-ntfs3 .ipk files (if it works this way) so one can manually install them directly on their device?

**Comment by xhikarishii** [comment]
Closing this, basic USB Drive and filesystem will be included on the next release :)
