### ISSUE TITLE
Great God, you can opclash and passwall to your firmware？

### ISSUE THREAD

**Issue by qwer155168** [xhikarishii/openwrt-ipq#6]
I tried to install it myself, and many of them relied on reporting errors.

**Comment by xhikarishii** [comment]
I can have a look into adding openclash to the build

**Comment by qwer155168** [comment]
> 我可以考虑将 openclash 添加到构建中

OK, thank you for your reply, I will wait for your update again

**Comment by xhikarishii** [comment]
Closing, will include a separate build with pre-installed openclash.
