### ISSUE TITLE
I tried to pull the source code to build the firmware myself, but I encountered an error

### ISSUE THREAD

**Issue by qwer155168** [xhikarishii/openwrt-ipq#7]
I don’t know if it has something to do with this
![QQ截图20240908205657](https://github.com/user-attachments/assets/4f4f68b0-6f7e-4f56-81b9-dcf878054ad4)
This is the error log： ERROR: package/feeds/nss_packages/qca-nss-ecm failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/wang/openwrt-ipq/include/toplevel.mk:248：world] 错误 1

**Comment by qwer155168** [comment]
Tried again using make V=s -j1 I got the detailed error： /home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1/frontends/nss/ecm_nss_non_ported_ipv4.c: In function 'ecm_nss_non_ported_ipv4_connection_accelerate':
/home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1/frontends/nss/ecm_nss_non_ported_ipv4.c:859:47: error: 'NSS_IPV4_RULE_CREATE_RAWIP_VALID' undeclared (first use in this function); did you mean 'NSS_IPV4_RULE_CREATE_RPS_VALID'?
  859 |                         nircm->valid_flags |= NSS_IPV4_RULE_CREATE_RAWIP_VALID;
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                               NSS_IPV4_RULE_CREATE_RPS_VALID
/home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1/frontends/nss/ecm_nss_non_ported_ipv4.c:859:47: note: each undeclared identifier is reported only once for each function it appears in
make[6]: *** [scripts/Makefile.build:243: /home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1/frontends/nss/ecm_nss_non_ported_ipv4.o] Error 1
make[5]: *** [/home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.44/Makefile:1921: /home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[4]: Leaving directory '/home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.44'
make[3]: *** [Makefile:191: /home/wang/openwrt-ipq/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/qca-nss-ecm-12.5.2024.06.20~92c7fa1/.built] Error 2
make[3]: Leaving directory '/home/wang/openwrt-ipq/feeds/nss_packages/qca-nss-ecm'
time: package/feeds/nss_packages/qca-nss-ecm/compile#0.36#0.68#1.03
    ERROR: package/feeds/nss_packages/qca-nss-ecm failed to build.
make[2]: *** [package/Makefile:173: package/feeds/nss_packages/qca-nss-ecm/compile] Error 1
make[2]: Leaving directory '/home/wang/openwrt-ipq'
make[1]: *** [package/Makefile:167: /home/wang/openwrt-ipq/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/wang/openwrt-ipq'
make: *** [/home/wang/openwrt-ipq/include/toplevel.mk:248：world] 错误 2
![QQ截图20240908213019](https://github.com/user-attachments/assets/9785e58e-8a07-40cd-9b09-555607832be7)

**Comment by xhikarishii** [comment]
Can you try updating your local now? I just pulled new updates from upstream. Also make sure per-requisites are installed.

**Comment by qwer155168** [comment]
> 您现在可以尝试更新本地吗？我刚刚从上游提取了新的更新。另外请确保安装了必备软件。

ok i will try again

**Comment by xhikarishii** [comment]
Hi @qwer155168 

I was able to replicate the issue, this issue seems to appear on firmware version 12.5 of NSS, please switch to version 11.4 as it's the most stable right now.

**Comment by xhikarishii** [comment]
I had rolled back the repository to last known working, you can try clone and pull again

**Comment by xhikarishii** [comment]
This issue is fixed, see [fix here](https://github.com/xhikarishii/nss-packages/compare/23d5aaaf3fb092d605ad40beea3585aac63250ee...aa57d9c4820559021f2b0d7db9496e28bf503058)
