### ISSUE TITLE
Adguard home?

### ISSUE THREAD

**Issue by apa-u** [xhikarishii/openwrt-ipq#9]
Hi Hikari! I’m here to ask you something. Have you tried running AdGuard on your AW1000? How did it go? I’m thinking of installing AdGuard and uninstalling the default adblock, but I’m not sure if it might cause problems with your build. I’d really appreciate your help with this! Thanks a bunch!

**Comment by xhikarishii** [comment]
Hi @apa-u 

Yes you can install adguard and remove the default adblock, I don't think there would be an issue doings so :)
